# yaml-language-server: $schema=https://raw.githubusercontent.com/sighupio/distribution/v1.31.1/schemas/public/onpremises-kfd-v1alpha2.json
---
apiVersion: kfd.sighup.io/v1alpha2
kind: OnPremises
metadata:
  name: demo-cluster
spec:
  distributionVersion: v1.31.1
  kubernetes:
    pkiFolder: ./pki
    ssh:
      username: demo
      keyPath: ../out/id_rsa
    dnsZone: example.dev
    controlPlaneAddress: demo-control-plane-0.example.dev:6443
    podCidr: 172.16.128.0/17
    svcCidr: 172.16.0.0/17
    loadBalancers:
      enabled: false
    masters:
      hosts:
        - name: demo-control-plane-0
          ip: 192.168.1.40
    nodes:
      - name: worker
        hosts:
          - name: demo-node-0
            ip: 192.168.1.45
          - name: demo-node-1
            ip: 192.168.1.46
          - name: demo-node-2
            ip: 192.168.1.47
  distribution:
    modules:
      networking:
        type: "calico"
      ingress:
        baseDomain: internal.example.dev
        nginx:
          type: single
          tls:
            provider: certManager
        certManager:
          clusterIssuer:
            name: letsencrypt-fury
            email: example@sighup.io
            type: http01
      logging:
        type: loki
        loki:
          tsdbStartDate: "2024-11-20"
        minio:
          storageSize: "20Gi"
      monitoring:
        type: "prometheus"
      tracing:
        type: none
      policy:
        type: none
      dr:
        type: none
      auth:
        provider:
          type: none
        baseDomain: example.dev
  plugins:
    kustomize:
      - name: storage
        folder: https://github.com/rancher/local-path-provisioner/deploy?ref=v0.0.31
