---
- name: Append custom entries to hosts files on all nodes
  hosts: all
  become: true

  vars:
    cluster_hosts: "{{ lookup('file', 'hosts') }}"

  tasks:
    - name: Append to /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ cluster_hosts }}"

    - name: Append to /etc/cloud/templates/hosts.debian.tmpl
      ansible.builtin.blockinfile:
        path: /etc/cloud/templates/hosts.debian.tmpl
        block: "{{ cluster_hosts }}"
